# Generated by Django 4.0.4 on 2022-05-24 07:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مبلغ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیجات')),
                ('name', models.CharField(max_length=50, verbose_name='نام منبع')),
                ('receive_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ شروع دریافت')),
                ('type', models.CharField(choices=[('DAY', 'روزانه'), ('WEK', 'هفتگی'), ('MON', 'ماهانه'), ('YEA', 'سالیانه')], default='MON', max_length=3, verbose_name='نوع دریافت')),
            ],
            options={
                'verbose_name': 'منبع خرج',
                'verbose_name_plural': 'منابع خرج',
            },
        ),
    ]
