# Generated by Django 4.0.4 on 2022-05-29 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_Saving', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saving',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیجات'),
        ),
        migrations.CreateModel(
            name='SavingPaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مبلغ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیجات')),
                ('payment_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان پرداخت')),
                ('saving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='app_Saving.saving', verbose_name='صندوق پس انداز')),
            ],
            options={
                'verbose_name': 'پرداخت پس انداز',
                'verbose_name_plural': 'پرداختی های پس انداز',
            },
        ),
    ]
