# Generated by Django 4.0.4 on 2022-06-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Saving', '0003_alter_saving_amount_alter_savingpaymentlog_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingpaymentlog',
            name='type',
            field=models.CharField(choices=[('WID', 'برداشت'), ('DEP', 'واریز')], default='DEP', max_length=3, verbose_name='نوع پرداخت'),
        ),
    ]
