# Generated by Django 4.0.4 on 2022-05-25 09:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مبلغ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیجات')),
                ('name', models.CharField(max_length=50, verbose_name='اسم قبض')),
                ('payment_date_time', models.DateTimeField(default=datetime.datetime(2022, 5, 25, 9, 37, 55, 832373, tzinfo=utc), verbose_name='زمان پرداخت')),
                ('tracking_code', models.CharField(max_length=50, verbose_name='کد رهگیری')),
                ('type', models.CharField(choices=[('PHN', 'تلفن'), ('ELC', 'برق'), ('WTR', 'آب'), ('GAS', 'گاز'), ('TAX', 'مالیات')], max_length=3, verbose_name='نوع قبض')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'قبض',
                'verbose_name_plural': 'قبوض',
            },
        ),
    ]
