# Generated by Django 4.0.4 on 2022-05-25 09:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_Receipt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='payment_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان پرداخت'),
        ),
    ]
