# Generated by Django 4.0.4 on 2022-06-01 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='مبلغ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیجات')),
                ('person', models.CharField(max_length=100, verbose_name='نام شخص')),
                ('check_number', models.IntegerField(verbose_name='شماره چک')),
                ('check_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ وصول')),
                ('type', models.CharField(choices=[('PAY', 'پرداختی'), ('REC', 'دریافتی')], default='PAY', max_length=3, verbose_name='نوع')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='سازنده')),
            ],
            options={
                'verbose_name': 'چک',
                'verbose_name_plural': 'چک ها',
            },
        ),
    ]
