# Generated by Django 4.0.4 on 2022-06-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Checks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='status',
            field=models.CharField(choices=[('DUR', 'در جریان'), ('SUC', 'وصول شده'), ('FIL', 'عدم وصول')], default='DUR', max_length=3, verbose_name='وضعیت'),
        ),
    ]
