# Generated by Django 4.0.4 on 2022-05-24 07:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DebtAndDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مبلغ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیجات')),
                ('person', models.CharField(max_length=100, verbose_name='نام شخص')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('type', models.CharField(choices=[('DEB', 'بدهی'), ('DEM', 'طلب')], default='DEB', max_length=3, verbose_name='نوع')),
                ('status', models.CharField(choices=[('CLS', 'بایگانی'), ('OPN', 'جاری')], default='OPN', max_length=3, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'بدهی و طلب',
                'verbose_name_plural': 'بدهی و طلب ها',
            },
        ),
    ]
