# Generated by Django 4.0.4 on 2022-06-08 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CHK', 'چک'), ('BIL', 'منبع خرج'), ('INS', 'قسط'), ('DBM', 'بدهی و طلب')], default='INS', max_length=3, verbose_name='دسته اطلاع رسانی')),
                ('time_notice', models.CharField(choices=[('WEK', '۱ هفته قبل'), ('TDY', '۲ روز قبل'), ('DAY', '۱ روز قبل')], default='DAY', max_length=3, verbose_name='زمان اطلاع رسانی')),
                ('notice_type', models.CharField(choices=[('EML', 'ایمیل'), ('PNL', 'پنل کاربری')], default='PNL', max_length=3, verbose_name='نوع اطلاع رسانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تنظیمات اطلاع رسانی',
                'verbose_name_plural': 'تنظیمات اطلاع رسانی ها',
            },
        ),
    ]
