# Generated by Django 4.0.4 on 2022-06-08 10:36

import app_Options.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Options', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationoptions',
            name='type',
            field=models.CharField(choices=[('CHK', 'چک'), ('BIL', 'منبع خرج'), ('INS', 'قسط'), ('DBM', 'بدهی و طلب')], default='INS', max_length=3, validators=[app_Options.models.unique_type_validator], verbose_name='دسته اطلاع رسانی'),
        ),
    ]
