# Generated by Django 4.0.4 on 2022-05-25 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Installments', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installmentpayments',
            old_name='payment_date',
            new_name='payment_date_time',
        ),
    ]
