# Generated by Django 4.0.4 on 2022-05-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Installments', '0003_rename_payment_date_installmentpayments_payment_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentpayments',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیجات'),
        ),
        migrations.AddField(
            model_name='installments',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیجات'),
        ),
    ]
