# Generated by Django 4.0.4 on 2022-05-29 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Installments', '0004_installmentpayments_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installmentpayments',
            name='description',
        ),
    ]
