# Generated by Django 4.0.4 on 2022-07-09 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_Transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='مبلغ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیجات')),
                ('type', models.CharField(choices=[('BIL', 'درآمد'), ('CHK', 'چک'), ('DBM', 'بدهی و طلب'), ('INS', 'قسط'), ('RCP', 'قبض'), ('SVG', 'پس انداز'), ('MRE', 'اضافی')], default='MRE', max_length=3, verbose_name='نوع تراکنش')),
                ('reference_id', models.IntegerField(null=True, verbose_name='ایدی منبع')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('condition', models.CharField(choices=[('ADT', 'اضافه'), ('DET', 'کسر')], default='ADT', max_length=3, verbose_name='وضعیت تراکنش')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کیف پول',
                'verbose_name_plural': 'کیف پول ها',
            },
        ),
    ]
