# Generated by Django 4.0.4 on 2022-07-15 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Transactions', '0003_alter_transaction_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['created_date'], 'verbose_name': 'کیف پول', 'verbose_name_plural': 'کیف پول ها'},
        ),
    ]
